# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
   

    config.vm.provision "shell", inline: "echo Provisionning 4 RHEL7 machines for ELK"

    config.vm.define "elastic-1" do |elastic1|
        elastic1.vm.box = "generic/rhel7"
        elastic1.vm.box_check_update = false
        elastic1.vm.network "private_network", ip: "192.168.33.100"
        elastic1.vm.network "forwarded_port", id: "ssh", host: 22222, guest: 22
        elastic1.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end

        elastic1.vm.provision "file", source: "./id_rsa.pub", destination: "~/.ssh/ansible.pub"
        elastic1.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys
        SHELL
    end

    config.vm.define "elastic-2" do |elastic2|
        elastic2.vm.box = "generic/rhel7"
        elastic2.vm.box_check_update = false
        elastic2.vm.network "private_network", ip: "192.168.33.101"
        elastic2.vm.network "forwarded_port", id: "ssh", host: 22223, guest: 22
        elastic2.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end

        elastic2.vm.provision "file", source: "./id_rsa.pub", destination: "~/.ssh/ansible.pub"
        elastic2.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys
        SHELL
    end

    config.vm.define "elastic-3" do |elastic3|
        elastic3.vm.box = "generic/rhel7"
        elastic3.vm.box_check_update = false
        elastic3.vm.network "private_network", ip: "192.168.33.102"
        elastic3.vm.network "forwarded_port", id: "ssh", host: 22224, guest: 22
        elastic3.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
        end

        elastic3.vm.provision "file", source: "./id_rsa.pub", destination: "~/.ssh/ansible.pub"
        elastic3.vm.provision "shell", inline: <<-SHELL
            cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys
        SHELL
    end
  
    
  
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine. In the example below,
    # accessing "localhost:8080" will access port 80 on the guest machine.
    # NOTE: This will enable public access to the opened port
    # config.vm.network "forwarded_port", guest: 80, host: 8080
  
  
    # Create a forwarded port mapping which allows access to a specific port
    # within the machine from a port on the host machine and only allow access
    # via 127.0.0.1 to disable public access
    # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  
    # Create a private network, which allows host-only access to the machine
    # using a specific IP.
    # config.vm.network "private_network", ip: "192.168.33.10"
  
    # Create a public network, which generally matched to bridged network.
    # Bridged networks make the machine appear as another physical device on
    # your network.
    # config.vm.network "public_network"
  
    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    # config.vm.synced_folder "../data", "/vagrant_data"
  
    # Provider-specific configuration so you can fine-tune various
    # backing providers for Vagrant. These expose provider-specific options.
    # Example for VirtualBox:
    #
    # config.vm.provider "virtualbox" do |vb|
    #   # Display the VirtualBox GUI when booting the machine
    #   vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    #   vb.memory = "1024"
    # end
    #
    # View the documentation for the provider you are using for more
    # information on available options.
  
  end